# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: Dockerfile.default
    ports:
      - 5008:5008
